name: sprngr.com build
on:
  push:
    branches:
      - master
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run build
      - name: deploy
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_ADDRESS: ${{ secrets.REMOTE_ADDRESS }}
        run: |
          npm run deploy
